//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AURA_DBContext : DbContext
    {
        public AURA_DBContext()
            : base("name=AURA_DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ao> Aos { get; set; }
        public virtual DbSet<ChiTietSanPhamAo> ChiTietSanPhamAos { get; set; }
        public virtual DbSet<ChiTietSanPhamGU> ChiTietSanPhamGUs { get; set; }
        public virtual DbSet<ChiTietSanPhamPhuKien> ChiTietSanPhamPhuKiens { get; set; }
        public virtual DbSet<ChiTietSanPhamQuan> ChiTietSanPhamQuans { get; set; }
        public virtual DbSet<ChiTietSanPhamTrangChu> ChiTietSanPhamTrangChus { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DanhMucAo> DanhMucAos { get; set; }
        public virtual DbSet<DanhMucPhuKien> DanhMucPhuKiens { get; set; }
        public virtual DbSet<DanhMucQuan> DanhMucQuans { get; set; }
        public virtual DbSet<Gu> Gus { get; set; }
        public virtual DbSet<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        public virtual DbSet<NhomSanPham> NhomSanPhams { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PhuKien> PhuKiens { get; set; }
        public virtual DbSet<Quan> Quans { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<SanPhamAo> SanPhamAos { get; set; }
        public virtual DbSet<SanPhamPhuKien> SanPhamPhuKiens { get; set; }
        public virtual DbSet<SanPhamQuan> SanPhamQuans { get; set; }
        public virtual DbSet<Tram> Trams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<v_SanPhamDanhMuc> v_SanPhamDanhMuc { get; set; }
        public virtual DbSet<View_SanPhamTong> View_SanPhamTong { get; set; }
    }
}
