//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPhamPhuKien
    {
        public int MaCT { get; set; }
        public int MaSP { get; set; }
        public string ChatLieu { get; set; }
        public string XuatXu { get; set; }
        public string PhuHop { get; set; }
        public string BaoHanh { get; set; }
    
        public virtual SanPhamPhuKien SanPhamPhuKien { get; set; }
    }
}
