//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucAo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucAo()
        {
            this.SanPhamAos = new HashSet<SanPhamAo>();
        }
    
        public int MaDM { get; set; }
        public Nullable<int> MaDMCha { get; set; }
        public string TenDM { get; set; }
        public string Banner { get; set; }
    
        public virtual Ao Ao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamAo> SanPhamAos { get; set; }
    }
}
