//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhomSanPham()
        {
            this.ChiTietSanPhamGUs = new HashSet<ChiTietSanPhamGU>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int NhomID { get; set; }
        public Nullable<int> TramID { get; set; }
        public string TenNhom { get; set; }
        public string MoTa { get; set; }
        public string HinhAnhBanner { get; set; }
        public string HinhAnh { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSanPhamGU> ChiTietSanPhamGUs { get; set; }
        public virtual Tram Tram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
