//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tram()
        {
            this.NhomSanPhams = new HashSet<NhomSanPham>();
        }
    
        public int TramID { get; set; }
        public Nullable<int> GuID { get; set; }
        public string TenTram { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual Gu Gu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomSanPham> NhomSanPhams { get; set; }
    }
}
