//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SanPhamTong
    {
        public string SanPhamID { get; set; }
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string MauSac { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<int> NhomID { get; set; }
        public string LoaiSP { get; set; }
    }
}
