//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AURA_DBContext : DbContext
    {
        public AURA_DBContext()
            : base("name=AURA_DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<Gu> Gus { get; set; }
        public virtual DbSet<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        public virtual DbSet<NhomSanPham> NhomSanPhams { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<Tram> Trams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<v_SanPhamDanhMuc> v_SanPhamDanhMuc { get; set; }
    
        public virtual ObjectResult<sp_GetAllSanPham_Result> sp_GetAllSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllSanPham_Result>("sp_GetAllSanPham");
        }
    }
}
