//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AURA.Models.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SanPhamDanhMuc
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string MauSac { get; set; }
        public string MoTaSP { get; set; }
        public string HinhAnh { get; set; }
        public string DanhMuc { get; set; }
        public string MoTaDM { get; set; }
    }
}
